version: "3.8"

services:
  api:
    container_name: api
    build:
      context: ./services/api
      target: production
    env_file:
      - ./@env/main.env
    restart: on-failure
    command: npm run start:prod
    network_mode: host

  discord:
    container_name: discord
    build:
      context: ./services/discord
      target: production
    env_file:
      - ./@env/main.env
    restart: on-failure
    command: npm run start:prod
    network_mode: host

  gateway:
    container_name: gateway
    build:
      context: ./services/gateway
      target: production
    env_file:
      - ./@env/main.env
    restart: on-failure
    command: npm run start:prod
    network_mode: host

  gateway-socket:
    container_name: gateway-socket
    build:
      context: ./services/gateway-socket
      target: production
    env_file:
      - ./@env/main.env
    restart: on-failure
    command: npm run start:prod
    ports:
      - "5000:5000"
    network_mode: host

  skillrank:
    container_name: skillrank
    build:
      context: ./services/skillrank
      target: production
    env_file:
      - ./@env/main.env
    restart: on-failure
    command: npm run start:prod
    network_mode: host

  steam:
    container_name: steam
    build:
      context: ./services/steam
      target: production
    env_file:
      - ./@env/main.env
    restart: on-failure
    command: npm run start:prod
    network_mode: host
