version: "3.8"

services:
  api:
    container_name: api
    build:
      context: ./services/api
      target: production
    env_file:
      - ./@env/main.env
    restart: on-failure
    command: npm run start:prod

  discord:
    container_name: discord
    build:
      context: ./services/discord
      target: production
    env_file:
      - ./@env/main.env
    restart: on-failure
    command: npm run start:prod

  gateway:
    container_name: gateway
    build:
      context: ./services/gateway
      target: production
    env_file:
      - ./@env/main.env
    restart: on-failure
    command: npm run start:prod
    ports:
      - "3000:3000"

  gateway-socket:
    container_name: gateway-socket
    build:
      context: ./services/gateway-socket
      target: production
    env_file:
      - ./@env/main.env
    restart: on-failure
    command: npm run start:prod
    ports:
      - "5000:5000"

  skillrank:
    container_name: skillrank
    build:
      context: ./services/skillrank
      target: production
    env_file:
      - ./@env/main.env
    restart: on-failure
    command: npm run start:prod
